---
# tasks file for aws_create_subnet
- name: Create subnet for VPC {{ stat_created_vpc_id }} with name tag {{ subnet_name_tag }}
  amazon.aws.ec2_vpc_subnet:
    region: "{{ aws_region }}"
    az: "{{ subnet_az }}"
    vpc_id: "{{ stat_created_vpc_id }}"
    cidr: "{{ cidr_block }}"
    map_public: true
    wait_timeout: 600
    resource_tags:
      Name: "{{ subnet_name_tag }}"
      Provisioner: "{{ provisioner_tag }}"
      Created: "{{ created_tag }}"
  register: create_subnet
  until: create_subnet is not failed
  retries: 15

- name: Setting stats for future tasks
  ansible.builtin.set_stats:
    data:
      stat_created_subnet_id: "{{ create_subnet.subnet.id | default('') }}"
  when: create_subnet.subnet.id is defined

- name: Setting facts for future tasks
  ansible.builtin.set_fact:
    stat_created_subnet_id: "{{ create_subnet.subnet.id | default('') }}"
  when: create_subnet.subnet.id is defined
