---
# tasks file for aws_manage_sg
- name: Manage Security Group
  amazon.aws.ec2_security_group:
    name: "{{ aws_manage_sg_sg_name_tag }}"
    state: "{{ aws_manage_sg_sg_state }}"
    description: "Ansible Managed Security Group: {{ aws_manage_sg_sg_name_tag }} "
    region: "{{ aws_manage_sg_aws_region }}"
    purge_rules: false
    vpc_id: "{{ stat_created_vpc_id }}"
  register: managed_sg

- name: Manage Ingress Rules on the SG
  amazon.aws.ec2_security_group:
    name: "{{ sg_name_tag }}"
    state: "{{ aws_manage_sg_sg_state }}"
    description: "Ansible Managed Security Group: {{ sg_name_tag }} "
    region: "{{ aws_region }}"
    purge_rules: false
    vpc_id: "{{ stat_created_vpc_id }}"
    rules:
      - proto: "{{ itemp.protocol }}"
        ports:
          - "{{ itemp.port }}"
        cidr_ip: "{{ item.cidr }}"
        rule_desc: "{{ item.desc }}"
  with_items: "{{ tcp_ingress_ports }}"
  when: tcp_ingress_ports is defined and aws_manage_sg_sg_state | bool

- name: Setting stats for future tasks
  ansible.builtin.set_stats:
    data:
      stat_created_sg_id: "{{ managed_sg['group_id'] | default('') }}"
  when: managed_sg['group_id'] is defined

- name: Setting facts for future tasks
  ansible.builtin.set_fact:
    stat_created_sg_id: "{{ managed_sg['group_id'] | default('') }}"
  when: managed_sg['group_id'] is defined
